# Generated by Django 5.2.4 on 2025-08-08 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
