# Generated by Django 5.2.4 on 2025-08-08 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogList', '0002_blogpost_posted_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='posted_date',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
