# Generated by Django 5.2.4 on 2025-08-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogList', '0003_alter_blogpost_options_remove_blogpost_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_date', '-created_time']},
        ),
    ]
